---
name: "Docker Registry"
description: "The Docker Registry 2.0 implementation for storing and distributing Docker images"
version: "0.4"
slug: "docker_registry"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  LOG_LEVEL: info
  STORAGE_DELETE_ENABLED: false
schema:
  LOG_LEVEL: list(debug|info|warn|error)?
  STORAGE_DELETE_ENABLED: bool?

ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: port to access docker registry
